- name: checking vars preference
  hosts: local
  connection: local
  # vars:
  #   GREETING: "Play level variables"
  # vars_files:
  # - vars.yaml
  # vars_prompt:
  # - name: GREETING
  #   prompt: Please enter the greeting
  #   private: false # not confidential 
  tasks:
  - name: print the message
    # vars:
    #   GREETING: "Task level variables"
    ansible.builtin.debug:
      msg: "Hello from {{GREETING}}"
  
  - name: print all the facts
    # vars:
    #   GREETING: "Task level variables"
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

#1. from args
#2. task level variables
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles