- name: create expense servers and r53 records
  connection: local
  hosts: local
  tasks:
  - name: ansible to install pymysql
    ansible.builtin.pip:
      name: 
      - cryptography
      - PyMySQL
      - boto3
      - botocore
      executable: pip3.9
  - name: Fetch secret from AWS Secrets Manager
    debug:
      msg: "The MySQL root password is {{ lookup('aws_secret', 'my-secret-name') }}"